### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by phanrahan** [leonardt/fault#183]
Lots of tests fail for me. Not sure what changed.
```
% pytest -s examples/test_simple_alu.py 
/Users/hanrahan/miniconda3/lib/python3.7/site-packages/pysmt/walkers/generic.py:43: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if len(nodetypes) == 1 and isinstance(nodetypes[0], collections.Iterable):
/Users/hanrahan/miniconda3/lib/python3.7/site-packages/ast_tools/immutable_ast.py:10: UserWarning: /Users/hanrahan/miniconda3/lib/python3.7/site-packages/ast_tools/immutable_ast.py generated for (3, 6)does not match system version (3, 7)
  warnings.warn(f"{__file__} generated for (3, 6)"
============================= test session starts ==============================
platform darwin -- Python 3.7.5, pytest-5.3.1, py-1.8.0, pluggy-0.13.1
rootdir: /Users/hanrahan/git/fault, inifile: setup.cfg
plugins: astropy-header-0.1.1, arraydiff-0.3, codestyle-2.0.0, remotedata-0.3.2, openfiles-0.4.0, profiling-1.7.0, doctestplus-0.5.0
collected 7 items                                                              

examples/test_simple_alu.py /Users/hanrahan/git/coreir/src/binary/coreir.cpp:188 Running Runningvpasses
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:10 In Run Generators
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:26 Done running generators
/Users/hanrahan/git/coreir/src/binary/coreir.cpp:197 Running vpasses
/Users/hanrahan/git/coreir/src/binary/coreir.cpp:238 Modified?: Yes
./Users/hanrahan/git/coreir/src/binary/coreir.cpp:188 Running Runningvpasses
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:10 In Run Generators
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:26 Done running generators
/Users/hanrahan/git/coreir/src/binary/coreir.cpp:197 Running vpasses
/Users/hanrahan/git/coreir/src/binary/coreir.cpp:238 Modified?: Yes
./Users/hanrahan/git/coreir/src/binary/coreir.cpp:188 Running Runningvpasses
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:10 In Run Generators
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:26 Done running generators
/Users/hanrahan/git/coreir/src/binary/coreir.cpp:197 Running vpasses
/Users/hanrahan/git/coreir/src/binary/coreir.cpp:238 Modified?: Yes
./Users/hanrahan/git/coreir/src/binary/coreir.cpp:188 Running Runningvpasses
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:10 In Run Generators
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:26 Done running generators
/Users/hanrahan/git/coreir/src/binary/coreir.cpp:197 Running vpasses
/Users/hanrahan/git/coreir/src/binary/coreir.cpp:238 Modified?: Yes
./Users/hanrahan/git/coreir/src/binary/coreir.cpp:188 Running Runningvpasses
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:10 In Run Generators
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:26 Done running generators
/Users/hanrahan/git/coreir/src/binary/coreir.cpp:197 Running vpasses
/Users/hanrahan/git/coreir/src/binary/coreir.cpp:238 Modified?: Yes
./Users/hanrahan/git/coreir/src/binary/coreir.cpp:188 Running Runningvpasses
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:10 In Run Generators
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:26 Done running generators
/Users/hanrahan/git/coreir/src/binary/coreir.cpp:197 Running vpasses
/Users/hanrahan/git/coreir/src/binary/coreir.cpp:238 Modified?: Yes
Running command: verilator -Wall -Wno-INCABSPATH -Wno-DECLFILENAME -Wno-fatal --cc SimpleALU.v --exe SimpleALU_driver.cpp --top-module SimpleALU
<STDERR>
%Error: SimpleALU.v:39: syntax error, unexpected IDENTIFIER, expecting ')' or ','
module commonlib_muxn__N2__width2 (input [1:0] \in_data_0/*verilator public*/ , input [1:0] \in_data_1/*verilator public*/ , input [0:0] \in_sel/*verilator public*/ , output [1:0] \out/*verilator public*/ );
                                                                     ^~~~~~
%Error: SimpleALU.v:41: syntax error, unexpected IDENTIFIER
coreir_mux #(.width(2)) _join(.in0(in_data_0), .in1(in_data_1), .out(_join_out), .sel(in_sel[0]));
^~~~~~~~~~
%Error: SimpleALU.v:45: syntax error, unexpected IDENTIFIER, expecting ')' or ','
module commonlib_muxn__N2__width16 (input [15:0] \in_data_0/*verilator public*/ , input [15:0] \in_data_1/*verilator public*/ , input [0:0] \in_sel/*verilator public*/ , output [15:0] \out/*verilator public*/ );
                                                                       ^~~~~~
%Error: SimpleALU.v:47: syntax error, unexpected IDENTIFIER
coreir_mux #(.width(16)) _join(.in0(in_data_0), .in1(in_data_1), .out(_join_out), .sel(in_sel[0]));
^~~~~~~~~~
%Error: SimpleALU.v:51: syntax error, unexpected IDENTIFIER, expecting ')' or ','
module commonlib_muxn__N4__width16 (input [15:0] \in_data_0/*verilator public*/ , input [15:0] \in_data_1/*verilator public*/ , input [15:0] \in_data_2/*verilator public*/ , input [15:0] \in_data_3/*verilator public*/ , input [1:0] \in_sel/*verilator public*/ , output [15:0] \out/*verilator public*/ );
                                                                       ^~~~~~
%Error: SimpleALU.v:57: syntax error, unexpected IDENTIFIER
coreir_mux #(.width(16)) _join(.in0(muxN_0_out), .in1(muxN_1_out), .out(_join_out), .sel(in_sel[1]));
^~~~~~~~~~
%Error: SimpleALU.v:65: syntax error, unexpected IDENTIFIER, expecting ')' or ','
module Mux4xOutUInt16 (input [15:0] \I0/*verilator public*/ , input [15:0] \I1/*verilator public*/ , input [15:0] \I2/*verilator public*/ , input [15:0] \I3/*verilator public*/ , output [15:0] \O/*verilator public*/ , input [1:0] \S/*verilator public*/ );
                                                   ^~~~~~
%Error: SimpleALU.v:67: syntax error, unexpected IDENTIFIER
commonlib_muxn__N4__width16 coreir_commonlib_mux4x16_inst0(.in_data_0(I0), .in_data_1(I1), .in_data_2(I2), .in_data_3(I3), .in_sel(S), .out(coreir_commonlib_mux4x16_inst0_out));
^~~~~~~~~~~~~~~~~~~~~~~~~~~
%Error: SimpleALU.v:71: syntax error, unexpected IDENTIFIER, expecting ')' or ','
module Mux2xOutBits2 (input [1:0] \I0/*verilator public*/ , input [1:0] \I1/*verilator public*/ , output [1:0] \O/*verilator public*/ , input \S/*verilator public*/ );
                                                 ^~~~~~
%Error: SimpleALU.v:73: syntax error, unexpected IDENTIFIER
commonlib_muxn__N2__width2 coreir_commonlib_mux2x2_inst0(.in_data_0(I0), .in_data_1(I1), .in_sel(S), .out(coreir_commonlib_mux2x2_inst0_out));
^~~~~~~~~~~~~~~~~~~~~~~~~~
%Error: SimpleALU.v:77: syntax error, unexpected '*', expecting ')' or ','
module Register_has_ce_True_has_reset_False_has_async_reset_False_has_async_resetn_False_type_Bits_n_2 (input \CE/*verilator public*/ , input \CLK/*verilator public*/ , input [1:0] \I/*verilator public*/ , output [1:0] \O/*verilator public*/ );
                                                                                                                                   ^
%Error: SimpleALU.v:80: syntax error, unexpected IDENTIFIER
Mux2xOutBits2 enable_mux(.I0(value_out), .I1(I), .O(enable_mux_O), .S(CE));
^~~~~~~~~~~~~
%Error: SimpleALU.v:85: syntax error, unexpected '*', expecting ')' or ','
module ConfigReg (input \CE/*verilator public*/ , input \CLK/*verilator public*/ , input [1:0] \D/*verilator public*/ , output [1:0] \Q/*verilator public*/ );
                                             ^
%Error: SimpleALU.v:87: syntax error, unexpected IDENTIFIER
Register_has_ce_True_has_reset_False_has_async_reset_False_has_async_resetn_False_type_Bits_n_2 conf_reg(.CE(CE), .CLK(CLK), .I(D), .O(conf_reg_O));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%Error: SimpleALU.v:91: syntax error, unexpected '*', expecting ')' or ','
module Add16_cin (input \CIN/*verilator public*/ , input [15:0] \I0/*verilator public*/ , input [15:0] \I1/*verilator public*/ , output [15:0] \O/*verilator public*/ );
                                              ^
%Error: SimpleALU.v:95: syntax error, unexpected IDENTIFIER
corebit_const #(.value(0)) bit_const_0_None(.out(bit_const_0_None_out));
^~~~~~~~~~~~~
%Error: SimpleALU.v:101: syntax error, unexpected IDENTIFIER, expecting ')' or ','
module Sub16 (input [15:0] \I0/*verilator public*/ , input [15:0] \I1/*verilator public*/ , output [15:0] \O/*verilator public*/ );
                                          ^~~~~~
%Error: SimpleALU.v:105: syntax error, unexpected IDENTIFIER
Add16_cin Add16_cin_inst0(.CIN(bit_const_1_None_out), .I0(I0), .I1(Invert16_inst0_out), .O(Add16_cin_inst0_O));
^~~~~~~~~
%Error: SimpleALU.v:111: syntax error, unexpected '*', expecting ')' or ','
module SimpleALU (input \CLK/*verilator public*/ , input [15:0] \a/*verilator public*/ , input [15:0] \b/*verilator public*/ , output [15:0] \c/*verilator public*/ , input [1:0] \config_data/*verilator public*/ , input \config_en/*verilator public*/ );
                                              ^
%Error: SimpleALU.v:118: syntax error, unexpected IDENTIFIER
Mux4xOutUInt16 Mux4xOutUInt16_inst0(.I0(coreir_add16_inst0_out), .I1(Sub16_inst0_O), .I2(coreir_mul16_inst0_out), .I3(xor16_inst0_out), .O(Mux4xOutUInt16_inst0_O), .S(config_reg_Q));
^~~~~~~~~~~~~~
%Error: Exiting due to 20 error(s)
</STDERR>
Found 1 error(s):
1) Got return code 1.
F/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:10 In Run Generators
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:26 Done running generators
/Users/hanrahan/git/coreir/src/binary/coreir.cpp:188 Running Runningvpasses
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:10 In Run Generators
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:26 Done running generators
/Users/hanrahan/git/coreir/src/binary/coreir.cpp:197 Running vpasses
/Users/hanrahan/git/coreir/src/binary/coreir.cpp:238 Modified?: No
/Users/hanrahan/miniconda3/lib/python3.7/site-packages/pysmt/walkers/generic.py:43: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if len(nodetypes) == 1 and isinstance(nodetypes[0], collections.Iterable):
Parsing file "build/SimpleALU.json"... /Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:10 In Run Generators
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:26 Done running generators
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:10 In Run Generators
/Users/hanrahan/git/coreir/src/passes/transform/rungenerators.cpp:26 Done running generators
DONE
Parsing file "build/SimpleALU.ets"... DONE
Solving "Problem 0_0" ........ TRUE

*** SUMMARY ***

** Problem Problem 0_0 **
Description: COMMAND LINE ASSERTION
Result: TRUE
Expected: TRUE
.

=================================== FAILURES ===================================
_________________ test_simple_alu_assume_guarantee[verilator] __________________

target = 'verilator'

    @pytest.mark.parametrize("target", ["verilator", "cosa"])
    def test_simple_alu_assume_guarantee(target):
        tester = fault.SymbolicTester(SimpleALU, SimpleALU.CLK, num_tests=100)
        tester.circuit.config_en = 1
        tester.circuit.config_data = 0
        tester.step(2)
        tester.circuit.config_en = 0
        tester.step(2)
        if target == "verilator":
            # NOTE: Currently the cosa backend does not support the expect action
            tester.circuit.config_reg.Q.expect(0)
        tester.circuit.a.assume(lambda a: a < BitVector[16](32768))
        tester.circuit.b.assume(lambda b: b < BitVector[16](32768))
        # tester.circuit.b.assume(lambda b: b >= BitVector[16](32768))
    
        tester.circuit.c.guarantee(lambda a, b, c: (c >= a) and (c >= b))
        kwargs = {}
        if target == "verilator":
            kwargs["flags"] = ["-Wno-fatal"]
            kwargs["magma_opts"] = {"verilator_debug": True}
        elif target == "cosa":
            kwargs["magma_opts"] = {"passes": ["rungenerators", "flatten",
                                               "cullgraph"]}
        os.system("rm -r build/*")
>       tester.compile_and_run(target, directory="build", **kwargs)

examples/test_simple_alu.py:93: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
fault/tester.py:308: in compile_and_run
    self._compile_and_run(target=target, **kwargs)
fault/tester.py:292: in _compile_and_run
    self._compile(target, **kwargs)
fault/tester.py:255: in _compile
    self.targets[target] = self.make_target(target, **kwargs)
fault/symbolic_tester.py:100: in make_target
    return super().make_target(target, **kwargs)
fault/tester.py:97: in make_target
    return VerilatorTarget(self._circuit, **kwargs)
fault/verilator_target.py:127: in __init__
    disp_type=self.disp_type)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = 'verilator -Wall -Wno-INCABSPATH -Wno-DECLFILENAME -Wno-fatal --cc SimpleALU.v --exe SimpleALU_driver.cpp --top-module SimpleALU'
cwd = PosixPath('build')
env = {'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.5jPbYy9EYr/Render', 'CDPATH': '.:/Users/hanrahan/git', 'DISPLAY': ':0', 'EDITOR': 'vi', ...}
disp_type = 'on_error', err_str = None, chk_ret_code = True, shell = True
use_fault_cfg = True

    def subprocess_run(args, cwd=None, env=None, disp_type='on_error', err_str=None,
                       chk_ret_code=True, shell=False, use_fault_cfg=True):
        # "Deluxe" version of subprocess.run that can display STDOUT lines as they
        # come in, looks for errors in STDOUT and STDERR (raising an exception if
        # one is found), and can check the return code from the subprocess
        # (raising an exception if non-zero).
        #
        # The return value is a CompletedProcess, which has properties
        # "returncode", "stdout", and "stderr".  This allows for further processing
        # of the results if desired.
        #
        # Note that only STDOUT is displayed in realtime; STDERR is displayed in
        # its entirety after the subprocess runs.  This is mainly to avoid the
        # confusion that arises when interleaving STDOUT and STDERR.
        #
        # args: List of arguments, with the same meaning as subprocess.run.
        #       Unlike subprocess.run, however, this should always be a list.
        # cwd: Directory in which to run the subprocess.
        # env: Dictionary representing the environment variables to be set
        #      while running the subprocess.  In None, defaults are determined
        #      based on one of the optional fault user config files.
        # disp_type: 'on_error', 'realtime'.  If 'on_error', only print if there
        #            is an error.  If 'realtime', print out STDOUT as lines come
        #            in, then print STDERR after the process completes.
        # err_str: If not None, look for err_str in each line of STDOUT and
        #          STDERR, raising an AssertionError if it is found.
        # chk_ret_code: If True, check the return code after the subprocess runs,
        #               raising an AssertionError if it is non-zero.
        # shell: If True, shell-quote arguments and concatenate using spaces into
        #        a string, then Popen with shell=True.  This is sometimes needed
        #        when running programs if they are actually scripts (e.g.,
        #        Verilator)
        # use_fault_cfg: If True (default) and env is None, then use FaultConfig
        #                to fill in default environment variables.
    
        # set defaults
        if env is None and use_fault_cfg:
            env = FaultConfig().get_sim_env()
    
        # set up printing
        display = PrintDisplay(mode=disp_type)
    
        # print out the command in a format that can be copy-pasted
        # directly into a terminal (i.e., with proper quoting of arguments)
        cmd_str = ' '.join(shlex.quote(arg) for arg in args)
        display.print(CYAN + BRIGHT + 'Running command: ' + RESET_ALL + cmd_str)
    
        # combine arguments into a string if needed for shell=True
        if shell:
            args = cmd_str
    
        # run the subprocess
        err_msg = []
        with Popen(args, cwd=cwd, env=env, stdout=PIPE, stderr=PIPE, bufsize=1,
                   universal_newlines=True, shell=shell) as p:
    
            # print out STDOUT, then STDERR
            # threads could be used here but pytest does not detect exceptions
            # in child threads, so for now the outputs are printed sequentially
            stdout = display.process_output(fd=p.stdout, name='STDOUT')
            stderr = display.process_output(fd=p.stderr, name='STDERR')
    
            # get return code and check result if desired
            returncode = p.wait()
    
            if chk_ret_code and returncode:
                err_msg += [f'Got return code {returncode}.']
    
            # look for errors in STDOUT or STDERR
            if err_str is not None:
                if err_str in stdout:
                    err_msg += [f'Found "{err_str}" in STDOUT.']
                if err_str in stderr:
                    err_msg += [f'Found "{err_str}" in STDERR.']
    
        # if any errors were found, print out STDOUT and STDERR if they haven't
        # already been printed, then print out what the error(s) were and
        # raise an exception
        if len(err_msg) != 0:
            display.error_printing()
            print(RED + BRIGHT + f'Found {len(err_msg)} error(s):' + RESET_ALL)
            for k, e in enumerate(err_msg):
                print(RED + BRIGHT + f'{k+1}) {e}' + RESET_ALL)
>           raise AssertionError
E           AssertionError

fault/subprocess_run.py:142: AssertionError
========================= 1 failed, 6 passed in 9.29s ==========================
% 
```

**Comment by leonardt** [comment]
The error messages look related to a bug that was fixed by https://github.com/rdaly525/coreir/pull/820

Can you try updating your coreir/verilogAST installation?

```
# update verilogAST source
cd /path/to/coreir/build/verilogAST-src
git pull
cd ..
# update coreir
git pull
# rebuild/install
make && make install
``

**Comment by leonardt** [comment]
Actually I was able to reproduce this, I think this was another regression introduced related to that original issue, looking into it

**Comment by phanrahan** [comment]
I did update coreir and the problem persisted.

**Comment by leonardt** [comment]
Should be fixed by https://github.com/rdaly525/coreir/pull/821

**Comment by phanrahan** [comment]
I just pulled the latest release of coreir and installed. Tests still fail for the same reason. Is there something else I ned to do?

**Comment by leonardt** [comment]
@phanrahan that branch hasn't been merged yet, waiting for a review, if you want to test the fix, you can check out the branch `hotfix-debug-port` in coreir and install it

**Comment by leonardt** [comment]
Branch has been merged/released, @phanrahan can you test it again with the latest coreir?

**Comment by phanrahan** [comment]
Works for me now.
